# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Run Jekyll on Windows'
url:              https://regal-arrow.cloudvent.net/
baseurl:          /

github:
  repo:           https://github.com/juthilo/run-jekyll-on-windows

author:
  name:           'AriefB'
  url:            https://twitter.com/riefb79
